services:
  quill:
    image: nginx:alpine
    container_name: quill-nginx
    volumes:
      - .deploy/quill.conf:/etc/nginx/conf.d/default.conf
      - static:/srv/playground/.static
    networks:
      proxy:
        ipv4_address: 172.20.0.102
      default:

  django:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    container_name: quill-django
    volumes:
      - static:/srv/playground/.static
    command: sh -c '
      python manage.py collectstatic --noinput &&
      python manage.py migrate --noinput &&
      gunicorn -c /srv/.deploy/gunicorn.py config.wsgi'
    networks:
      - default

volumes:
  static:

networks:
  proxy:
    external: true
