# Generated by Django 3.2 on 2021-05-01 19:05

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuillMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='QuillDetail2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_quill.fields.QuillField()),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.quillmaster')),
            ],
        ),
        migrations.CreateModel(
            name='QuillDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_quill.fields.QuillField()),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.quillmaster')),
            ],
        ),
    ]
